twitter/algebird

algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala
This 1-character change (essentially) should fix the problem described at #388 . :-)
=> GH-388: Fix CMS test issue caused by roundtripping depth->delta->depth

algebird-caliper/src/test/scala/com/twitter/algebird/caliper/CMSHashingBenchmark.scala, algebird-core/src/main/scala/com/twitter/algebird/CountMinSketch.scala, algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala
This PR addresses the issue described in #392.
In addition, this PR includes several CMS code fixes as well as CMS test/spec fixes that I described at #393.  The reason these fixes are included in the PR is that the hashing improvements for BigInt exposed these code bugs / test bugs, and excluding those fixes would have meant that we end up with non-working code.
On a high-level, the hashing improvement for `CMS[BigInt]` covers (cf. #392):
- We now use Murmur3-based hashing for `BigInt` instead of the "default" hashing implementation we use for `Long` and friends.  See #392 for the justification of using Murmur3 and for why this change in general is important for `BigInt` use cases.
On a high-level, the additional fixes cover (cf. #393):
- Fixes to how we estimate inner products of CMS.
- …
=> GH-392: Improve hashing of BigInt

algebird-core/src/main/scala/com/twitter/algebird/DecayedValue.scala, algebird-test/src/test/scala/com/twitter/algebird/DecayedValueTest.scala, algebird-util/src/test/scala/com/twitter/algebird/util/summer/AsyncListSumProperties.scala
DecayedValue's `average` method is useful but it gives artificially low results if the counter is only a small number of half lives old. `averageFrom` accounts for the fact that you might have a fixed bound in the past for your oldest value.
It currently requires passing an explicit endTime. I'm not sure if it's worth having a version which derives the endTime from the scaledTime (or possibly *only* having that version, and maybe adding a separate `asOf` method which can be used in conjunction... this seems better than having `valueAsOf` on the monoid, anyway).
=> add averageFrom to DecayedValue

algebird-core/src/main/scala/com/twitter/algebird/Applicative.scala, algebird-core/src/main/scala/com/twitter/algebird/Monad.scala, algebird-test/src/test/scala/com/twitter/algebird/ApplicativeProperties.scala, algebird-test/src/test/scala/com/twitter/algebird/MonadProperties.scala, algebird-util/src/main/scala/com/twitter/algebird/util/UtilAlgebras.scala, algebird-util/src/test/scala/com/twitter/algebird/util/summer/AsyncListSumProperties.scala
Cleaning up MonadSemigroup and friends, which always just used Applicative, but we didn't have that type class then.
=> Freshen up Applicative instances a bit

algebird-test/src/test/scala/com/twitter/algebird/TupleAggregatorsTest.scala, project/GenTupleAggregators.scala
Given MonoidAggregators as input, return a MonoidAggregator
instead of just a plain old Aggregator.
cc @avibryant
=> Return a MonoidAggregator from MultiAggregator when possible

.travis.yml, project/plugins.sbt
Lets try this again.
https://coveralls.io/r/twitter/algebird
Signed-off-by: Chris Aniszczyk <zx@twitter.com>
=> Add code coverage via coveralls

algebird-test/src/test/scala/com/twitter/algebird/TupleAggregatorsTest.scala, project/GenTupleAggregators.scala
Add a MapAggregator to join tuples of (K, Aggregator[A, Bn, C]) pairs
into a composed Aggregator[A, TupleN[B1,...,BN], Map[K, C]].
cc @avibryant @mlmanapat
=> Add MapAggregator to compose tuples of (key, agg) pairs

algebird-core/src/main/scala/com/twitter/algebird/Preparer.scala
Aggregators created through the Preparer interface retain references to the original Map/FlatMap Preparer instance. For Summingbird Storm jobs, this causes issues since the aggregators need to be Java serializable.
While we could try to construct the instances such that we don't retain any unnecessary references, it seems simpler to just make Preparer extend Serializable to avoid any issues in the future.
cc @avibryant
=> Make Preparer extend Serializable

algebird-core/src/main/scala/com/twitter/algebird/HyperLogLog.scala, algebird-test/src/test/scala/com/twitter/algebird/HyperLogLogTest.scala
A new function called "downsize" to safely reduce the size of a HyperLogLog sketch. The error rate goes up correspondingly due to loss of information. Based on the ideas presented in: [Set Operations On HLLs of Different Sizes](http://research.neustar.biz/2012/09/12/set-operations-on-hlls-of-different-sizes/) and its follow-up [HyperLogLog Engineering: Choosing The Right Bits](http://research.neustar.biz/2013/03/25/hyperloglog-engineering-choosing-the-right-bits/).
=> Added function to safely downsize a HyperLogLog sketch

algebird-core/src/main/scala/com/twitter/algebird/MapAlgebra.scala
Makes `MutableBackedMap` `Serializable` so that the result of `Semigroup.sumOption` can be serialized.
=> Make MutableBackedMap Serializable.

algebird-core/src/main/scala/com/twitter/algebird/Aggregator.scala, algebird-core/src/main/scala/com/twitter/algebird/Preparer.scala, algebird-core/src/main/scala/com/twitter/algebird/SummingCache.scala, algebird-test/src/test/scala/com/twitter/algebird/AggregatorLaws.scala
Don't merge this until we release 0.10.0. It breaks binary compatibility (adding methods to a trait). I tried to do it with an enrichment, but it hit a scala 2.10 compiler bug.
=> Add some combinators on MonoidAggregator

.travis.yml, algebird-caliper/src/test/scala/com/twitter/algebird/caliper/HLLBenchmark.scala, algebird-caliper/src/test/scala/com/twitter/algebird/caliper/HLLPresentBenchmark.scala, algebird-core/src/main/scala/com/twitter/algebird/Bytes.scala, algebird-core/src/main/scala/com/twitter/algebird/CountMinSketch.scala, algebird-core/src/main/scala/com/twitter/algebird/HyperLogLog.scala, algebird-test/src/test/scala/com/twitter/algebird/AggregatorLaws.scala, algebird-test/src/test/scala/com/twitter/algebird/BytesSpec.scala, algebird-test/src/test/scala/com/twitter/algebird/CollectionSpecification.scala, algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala, algebird-test/src/test/scala/com/twitter/algebird/HyperLogLogTest.scala
Benchmark results :
Old code:
https://gist.github.com/ianoc/980b369dd6d5354ce896
New code:
https://gist.github.com/ianoc/41afcafd7099948dbc84
Speedup: a little over 2.4x average ignoring outliers that would bias towards new code more(so if pathological cases new code still does better).
=> Adds a presenting benchmark and optimizes it

algebird-core/src/main/scala/com/twitter/algebird/Eventually.scala, algebird-core/src/main/scala/com/twitter/algebird/HyperLogLog.scala, algebird-test/src/test/scala/com/twitter/algebird/EventuallyTest.scala, algebird-test/src/test/scala/com/twitter/algebird/HyperLogLogTest.scala
An Aggregator that wraps the `EventuallySemigroup` (and one for `EventuallyMonoid`), as well as a `SetSizeAggregator` that starts with a `Set` and ends with a `HLL`.
=> EventuallyAggregator and variants

algebird-caliper/src/test/scala/com/twitter/algebird/caliper/AsyncSummerBenchmark.scala, algebird-caliper/src/test/scala/com/twitter/algebird/caliper/CMSHashingBenchmark.scala, algebird-caliper/src/test/scala/com/twitter/algebird/caliper/QTreeBenchmark.scala, algebird-core/src/main/scala/com/twitter/algebird/QTree.scala
This makes an algorithmic improvement, and uses sumOption to get pretty big wins in performance which should be enough for map/reduce applications. There are two tricks:
1) we don't need to scan the whole tree if the minCount is 1 or less, which is common, especially for smaller QTrees, which come up when you just add a few together which would be done in map-side aggregation.
2) in sumOption, we can wait to compress after we have added a number of items together. This can be controlled by the user but defaults to 25, which seems to be big enough to give a win in one of the benchmark cases, but also not so huge that I am nervous the QTree is going to get out of hand in size.
Also, I removed the `Monoid[A]` from the QTree instance, which was probably being serialized when people use Kryo, …
=> Speed up QTree

algebird-core/src/main/scala/com/twitter/algebird/HyperLogLog.scala, algebird-test/src/test/scala/com/twitter/algebird/HyperLogLogTest.scala
This should make it easier to create an Aggregator or HLL based on a desired error-rate rather than serialized size.
This is just a first step in making some of the more powerful aggregators easier to use.
=> Add HLL method to do error-based Aggregator

algebird-core/src/main/scala/com/twitter/algebird/MomentsGroup.scala, algebird-test/src/test/scala/com/twitter/algebird/MomentsGroupTest.scala
Typically, we require at least N samples in order to compute the N'th order moment. Currently, Moments returns values even when fewer than N samples -- these values are not meaningful, and should not be relied upon for very small sample size. This PR returns NaN in these cases, instead.
=> Moments returns NaN when count is too low for higher order statistics

algebird-core/src/main/scala/com/twitter/algebird/BloomFilter.scala, algebird-core/src/main/scala/com/twitter/algebird/HyperLogLog.scala, algebird-test/src/test/scala/com/twitter/algebird/BloomFilterTest.scala
Added possibility of HLL creation from pre-computed hashes to HyperLogLogMonoid.
This makes it possible to re-use pre-computed hashes and increase performance.
=> A couple of performance optimizations: HyperLogLog and BloomFilter

algebird-core/src/main/scala/com/twitter/algebird/HyperLogLog.scala, algebird-core/src/main/scala/com/twitter/algebird/HyperLogLogSeries.scala, algebird-test/src/test/scala/com/twitter/algebird/HyperLogLogSeriesTest.scala
This data structure can produce a HyperLogLog counter for any window into the past, using a constant factor more space than HyperLogLog.
For each hash bucket, rather than keeping a single max RhoW value, it keeps every RhoW value it has seen, and the max timestamp where it saw that value. This allows it to reconstruct an HLL as it would be had it started at zero at any given point in the past, and seen the same updates this structure has seen.
The usage is like this:
````scala
vall hllSeriesMonoid = new HyperLogLogSeriesMonoid(bits)
val series = examples
.map{case (bytes, timestamp) => hllSeriesMonoid.create(bytes, timestamp)}
.reduce{hllSeriesMonoid.plus(_,_)}
val estimate1 = series.since(timestamp1).toHLL.estimatedSize
val estimate2 = series.since(timestamp2).toHLL.estimatedSize
````
=> HyperLogLogSeries

algebird-core/src/main/scala/com/twitter/algebird/QTree.scala, algebird-test/src/test/scala/com/twitter/algebird/QTreeTest.scala
Assertion fails if percentile == 1.0, should pass if 0 <= percentile <= 1.0
=> QTree quantileBounds assert percentile <= 1.0

algebird-test/src/test/scala/com/twitter/algebird/HyperLogLogTest.scala
Replace instances of `new HyperLogLogMonoid(...).apply(...)`
with `new HyperLogLogMonoid(...).create(...)` in `HyperLogLogTest`.
=> Don't call deprecated HyperLogLog methods in tests

algebird-test/src/test/scala/com/twitter/algebird/TupleAggregatorsTest.scala, project/GenTupleAggregators.scala
- Make API easier to use (more consistent), by allowing to create a MapAggregator of one "metric"
improves: https://github.com/twitter/algebird/pull/411#issuecomment-104117951
=> Add MapAggregator from 1 (key, aggregator) pair

algebird-test/src/test/scala/com/twitter/algebird/TupleAggregatorsTest.scala, project/GenTupleAggregators.scala
- use string interpolation instead of .format()
- inline `prepare`, `present`, `semigroup`
- use more clear variable names:
- rename i to aggrCount
- rename nums to aggrNums
- rename semiType to semigroup (it refers to field name, not type), add semigroupType which actually refers to type
@johnynek
=> Refactor MapAggregator

algebird-benchmark/src/main/scala/com/twitter/algebird/benchmark/QTreeMicroBenchmark.scala, algebird-core/src/main/scala/com/twitter/algebird/QTree.scala, project/Build.scala
1) Internally use nullable instances of QTree rather than Option[QTree].
2) Specialize the class
3) Pre build an array with the range values rather than calculating pow(2, level) on each instanciation
Performance numbers:
Develop::
[info] Benchmark                           (depthK)  (numElements)  Mode  Cnt         Score         Error  Units
[info] QTreeBenchmark.timePlusDouble              6          10000  avgt   15  49604065.294 ±  343946.724  ns/op
[info] QTreeBenchmark.timePlusLong                6          10000  avgt   15  54040361.060 ±  451564.394  ns/op
[info] QTreeBenchmark.timePlusUnit                6          10000  avgt   15  52363803.668 ± 1403481.464  ns/op
[info] QTreeBenchmark.timeSumOptionDouble         6          10000  avgt   15  18536550.306 ±  102450.054  ns/op …
=> Optimize QTree a bunch

algebird-core/src/main/scala/com/twitter/algebird/CountMinSketch.scala, algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala
Closes #468
A bit of refactoring out duplicate code.  Leaving in `TopPctCMSAggregator` and `TopNCMSAggregator` so this should be binary compatible.
=> Adding scoped top-N CMS monoid

algebird-test/src/test/scala/com/twitter/algebird/VectorSpaceProperties.scala, project/Build.scala
Supersedes https://github.com/twitter/algebird/pull/431 as per @ianoc's suggestion, now with an even newer version of scalacheck and all tests passing locally (at least).
=> Upgrade scalacheck and scalatest

algebird-test/src/test/scala/com/twitter/algebird/NumericSpecification.scala, algebird-test/src/test/scala/com/twitter/algebird/TupleRing.scala
These tests were not running due to improper mixing of Scalacheck and Scalatest props.
=> Fix tests that were not actually running

algebird-benchmark/src/main/scala/com/twitter/algebird/benchmark/HLLPresentBenchmark.scala, algebird-core/src/main/scala/com/twitter/algebird/HyperLogLog.scala
This changes the use of `math.pow(2.0,-mj)` when computing the estimates in `SparseHLL` and `DenseHLL` to `1.0 / (1 << mj)`.
To benchmark the difference this makes, I first had to change the `HLLPresentBenchmark` to clone the `HLL` instances before asking for their `approximateSize`, otherwise the estimate gets cached as a lazy val and the benchmarks are meaningless.
Having done that, you can see a dramatic difference. Because I'm impatient I have so far only run this with a single set of parameters, where it led to a 40x speedup.
Before:
````
[info] Benchmark                            (bits)  (max)  (numHLL)   Mode  Cnt    Score   Error  Units
[info] HLLPresentBenchmark.timeBatchCreate      12  10000        10  thrpt  200  141.569 ± 5.010  ops/s
````
After:
````
[info] Benchmark …
```
=> Speed up HLL presentation by 100x

algebird-core/src/main/scala/com/twitter/algebird/Identity.scala, algebird-test/src/main/scala/com/twitter/algebird/MonadLaws.scala, algebird-test/src/test/scala/com/twitter/algebird/ApplicativeProperties.scala, algebird-test/src/test/scala/com/twitter/algebird/FunctorProperties.scala, algebird-test/src/test/scala/com/twitter/algebird/MonadProperties.scala
Having `Identity` around is useful for those of us writing `Applicative` and `Monad` heavy code.
=> Identity class and Monad instance

algebird-test/src/test/scala/com/twitter/algebird/BytesSpec.scala
A truncated array is only guaranteed to compare as less if the truncation happens at the end. Also we should be able to compare an empty Array so I'm not excluding the case where length == 1.
I've verified this by testing with a "\0" prefix on the random string (which makes the original code fail consistently).
Also testing empty arrays here.
Recreates #504
Fixes #503
=> Using dropRight instead of tail for shortening BytesSpec array

algebird-test/src/test/scala/com/twitter/algebird/MinHasherTest.scala
One `MinHasher32` being tested was using 247 hash functions internally, which
means that the expected absolute error bound:
1 / sqrt {# of hash functions} = 1 / sqrt 247  ~  0.064
The same test required an upper bound on the error of `0.05`, which was below
the expected error bound, meaning that this test would give flaky results due to
occasionally exceeding the required error bound.  This change increases the
upper bound on the error to 0.1 which should give enough headroom over the
expected error bound to reduce the number of random test failures.
=> Fix flaky `MinHasherSpec` test.  Fixes #500

algebird-core/src/main/scala/com/twitter/algebird/Operators.scala
I could be missing something obvious, but I think Operators.toRichTraversable should take a TraversableOnce instead of a Traversable. This will allow it to be less restrictive in the input types that it allows.
Currently:
```
scala> import com.twitter.algebird.Operators.toRichTraversable
scala> val x: Traversable[Int] = Traversable(1, 2, 3)
x: Traversable[Int] = List(1, 2, 3)
scala> x.monoidSum
res11: Int = 6
scala> val y: TraversableOnce[Int] = Traversable(1, 2, 3)
y: TraversableOnce[Int] = List(1, 2, 3)
scala> y.monoidSum
<console>:17: error: value monoidSum is not a member of TraversableOnce[Int]
y.monoidSum
^
```
With my fix:
```
scala> val y: TraversableOnce[Int] = Traversable(1, 2, 3)
y: TraversableOnce[Int] = List(1, 2, 3)
scala> y.monoidSum
res0: Int = 6
```
=> Fix the input type of Operators.toRichTraversable

build.sbt
While investigating some dbuild failures on our OSS projects, noticed that the scalaVersion in algebird was set to 2.10.x (this resulted in some cross-version compatibility issues). Setting it to 2.11.7 (we still create artifacts for 2.10.x).
=> Bump scala version

algebird-core/src/main/scala/com/twitter/algebird/SpaceSaver.scala, algebird-test/src/test/scala/com/twitter/algebird/SpaceSaverTest.scala
These constructors should have been private from the beginning. The documentation already says other constructors should be used instead.
Also a new constructor/apply is added to set the exact count of an item instead of default value of 1
=> make SSOne/SSMany constructors private and add apply method with count

algebird-test/src/test/scala/com/twitter/algebird/BytesSpec.scala
Fixes #524.  AFAICT there's no reason this appended byte should come from the original set of bytes.
=> Fixing BytesSpec to not reference head on an empty list

algebird-core/src/main/scala/com/twitter/algebird/Aggregator.scala
You can accomplish the same thing by passing Ordering.by(fn) directly to the sortedTake function, but I think adding these new functions makes the code a bit easier to use and will make downstream code more readable.
I didn’t see any existing unit tests on Aggregator.sortedTake, so I didn’t add any tests to this code. But would be willing to add some additional tests if we feel it is necessary.
=> Add sortedTakeBy and sortedReverseTakeBy to Aggregator.scala

algebird-core/src/main/scala/com/twitter/algebird/Aggregator.scala, algebird-core/src/main/scala/com/twitter/algebird/Batched.scala, algebird-test/src/test/scala/com/twitter/algebird/BatchedTest.scala
This is the free semigroup -- it represents combining one or more
elements using an associative operation. The values are stored in a
tree structure, which can be traversed. If a semigroup for the
underlying values becomes available, the structure can be summed to a
single value.
Batching represents a space/time trade-off (we use more space to use
less time). In some cases these structures may become too big. To
address this, there are constructors for `Monoid[Batched[A]]` and
`Semigroup[Batched[A]]` instances that will periodically compact
themselves (summing the tree to a single value) to keep the overall
size below a specific parameter.
Batching is appropriate anytime an eager concatenation or combination
will produce expensive intermediate values that will be thrown away, and a more …
=> Add Batched[A] type for efficient lazy addition

algebird-core/src/main/scala/com/twitter/algebird/Aggregator.scala
This is pretty minor, but QTreeAggregator and QTreeAggregatorLowerBound have default k values, so I think approximatePercentile and approximatePercentileBounds should also get the default k value. This might help out users who are new to QTrees :)
A small bit of testing:
```scala
scala> import com.twitter.algebird.Aggregator
import com.twitter.algebird.Aggregator
scala> val agg = Aggregator.approximatePercentile[Int](0.5)
agg: com.twitter.algebird.QTreeAggregatorLowerBound[Int] = QTreeAggregatorLowerBound(0.5,9)
scala> agg(Seq(1,2,3,4,5))
res4: Double = 3.0
```
=> Add a default k value for Aggregator.approximatePercentile

algebird-core/src/main/scala/com/twitter/algebird/MapAlgebra.scala, algebird-core/src/main/scala/com/twitter/algebird/Operators.scala, algebird-test/src/test/scala/com/twitter/algebird/CollectionSpecification.scala
In some personal code I wanted a 'MapAlgebra.group' analog to the 'TypedPipe.group' function:
```scala
def group[K, V](pairs: TraversableOnce[(K, V)]): Map[K, List[V]]
```
I think my implementation seems reasonably efficient, but I would be open to feedback if there was a better solution.
While I was at it, I added some additional documentation to MapAlgebra.sumByKey to mention that it filters out any keys where the values are 0. 
I also slightly updated the MapAlgebra.sumByKey unit test to (a) explicitly test that sumByKey drops values that are 0 and (b) test both the implicit and explicit version of the function.
I hope these changes all seem reasonable!
=> Add a MapAlgebra.group function

algebird-benchmark/src/main/scala/com/twitter/algebird/benchmark/CMSBenchmark.scala, algebird-benchmark/src/main/scala/com/twitter/algebird/benchmark/TopCMSBenchmark.scala, algebird-core/src/main/scala/com/twitter/algebird/CMSHasher.scala, algebird-core/src/main/scala/com/twitter/algebird/CountMinSketch.scala, algebird-core/src/main/scala/com/twitter/algebird/legacy/CountMinSketchMonoid.scala, algebird-test/src/main/scala/com/twitter/algebird/ApproximateProperty.scala, algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala, algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala
This PR updates the existing `CMS[A]` type to be more efficient, especially when summing many `CMS[A]` structures. The changes are expected to be binary-compatible. The only difference is that more efficient `CMSHasher` instances are available without an import (the import is still available for the legacy instances, which may be needed for old serialized data).
I've also updated the benchmarks to help demonstrate the changes. Here are the benchmarks from before any of the changes:
```
Benchmark                         (eps)  (size)    Cnt    Score     Error  Units
CMSBenchmark.sumLargeBigIntCms      0.1    1000     5   49.939 ±   1.152  ops/s
CMSBenchmark.sumLargeBigIntCms    0.005    1000     5   48.309 ±   2.453  ops/s
CMSBenchmark.sumLargeStringCms      0.1    1000     5   50.682 ± …
```
=> Optimize count-min sketch

.travis.yml, algebird-benchmark/src/main/scala/com/twitter/algebird/benchmark/CMSBenchmark.scala, algebird-benchmark/src/main/scala/com/twitter/algebird/benchmark/TopCMSBenchmark.scala, algebird-core/src/main/scala/com/twitter/algebird/CMSHasher.scala, algebird-core/src/main/scala/com/twitter/algebird/CountMinSketch.scala, algebird-core/src/main/scala/com/twitter/algebird/Operators.scala, algebird-spark/src/test/scala/com/twitter/algebird/spark/AlgebirdRDDTests.scala, algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala, algebird-test/src/test/scala/com/twitter/algebird/DecayedVectorProperties.scala, build.sbt
This does a few things:
1. adds mima backwards compatibility check as part of CI (long LONG overdue)
2. fixes some issues mima found.
3. removes the default `CMSHasher[BigInt]` which I am concerned was too weak of a hasher as it projects to `Int` before doing any mixing of the value `a`. We have a couple of proposals to improve that, but we should be sure we have something fast and correct before we make it default.
/cc @rubanm @isnotinvain @non @ianoc
=> Minor fixer for backwards compatibility (proposed 0.12.1)

algebird-core/src/main/scala/com/twitter/algebird/Field.scala, algebird-core/src/main/scala/com/twitter/algebird/Ring.scala, project/plugins.sbt
This can avoid some cases of double boxing. When we use for instance, `Semigroup[T]` and `T` happens to be `Long`, then we can still box despite the specialized call because `T` was generic where the `Semigroup` was used (I believe that is true).
Doing `sum` with plus means, unboxing the accumulator and the next item, adding them, boxing the result and starting again. This gives about `N` boxing operations and `2N` unboxing operations for `N` items to sum. If we do sum internally, we know the type, so we only have to unbox from the `TraverableOnce`, which gives `N` unboxing operations.
=> Add sumOption to Short,Int,Long,Float,Double

algebird-core/src/main/scala/com/twitter/algebird/Aggregator.scala, algebird-test/src/test/scala/com/twitter/algebird/AggregatorLaws.scala
I had to create a new PR with the suggested changes (due to the issue discussed [[here](https://github.com/isaacs/github/issues/361)](https://github.com/isaacs/github/issues/361)). Here was the previous [PR](https://github.com/twitter/algebird/pull/534).
This PR creates a numericSum aggregator which aggregates numeric values into Doubles.
Note that @johnynek suggested making this function specialized, but I tried that and the scala compiler complained.
The code was:
```scala
def numericSum[@specialized(Int, Long, Float, Double) T](implicit num: Numeric[T]): MonoidAggregator[T, Double, Double] =
Preparer[T].map(num.toDouble).monoidAggregate(Aggregator.fromMonoid)
```
And the error was:
```
[warn] /Users/jlande/work/github/algebird/algebird-core/src/main/scala/com/twitter/algebird/Aggregator …
```
=> Add a new Aggregator.numericSum function (second try)

algebird-spark/src/main/scala/com/twitter/algebird/spark/AlgebirdRDD.scala
Fixes https://github.com/twitter/algebird/issues/549.
Luckily repartition is equivalent to coalesce with shuffle true and it's signature didn't change. So the fix is pretty simple...
=> Fixes #549 - Use repartition instead of coalesce for compat with spark 2

algebird-core/src/main/scala/com/twitter/algebird/HyperLogLog.scala, algebird-core/src/main/scala/com/twitter/algebird/HyperLogLogSeries.scala, algebird-test/src/main/scala/com/twitter/algebird/ApproximateProperty.scala, algebird-test/src/test/scala/com/twitter/algebird/HyperLogLogSeriesTest.scala, algebird-test/src/test/scala/com/twitter/algebird/HyperLogLogTest.scala
This commit improves the performance of the HLLSeries data
structure. In particular, it introduces two new methods:
series.insert(bytes, timestamp)
series.approximateSizeSince(threshold)
Previously to add data to an HLLSeries required allocating another
series and then combining them with the monoid, potentially creating a
lot of garbage. The `insert` method does the same thing but without an
intermediate series.
Similarly, getting an approximate size used to require calling
`.toHLL` to build an HLL structure, and then asking that. By
abstracting out the machinery to actually do the HLL calculation,
we're able to do this directly from HLLSeries with
`approximateSizeSince`.
There are several other internal efficiency improvements. Some
independent benchmarks I've run show a 4-5x speed up …
=> Improve HLLSeries performance.

CONTRIBUTING.md
Instructions on the codecov browser extension and on how to write scalacheck and scalatest tests.
=> Add test-writing guide to `CONTRIBUTING.md`

algebird-core/src/main/scala/com/twitter/algebird/SketchMap.scala, algebird-core/src/main/scala/com/twitter/algebird/SpaceSaver.scala, algebird-test/src/main/scala/com/twitter/algebird/BaseProperties.scala, algebird-test/src/main/scala/com/twitter/algebird/MetricProperties.scala, algebird-test/src/main/scala/com/twitter/algebird/MonadLaws.scala, algebird-test/src/test/scala/com/twitter/algebird/AdJoinedUnitRingLaws.scala, algebird-test/src/test/scala/com/twitter/algebird/AveragedValueLaws.scala, algebird-test/src/test/scala/com/twitter/algebird/BatchedTest.scala, algebird-test/src/test/scala/com/twitter/algebird/CollectionSpecification.scala, algebird-test/src/test/scala/com/twitter/algebird/CountMinSketchTest.scala, algebird-test/src/test/scala/com/twitter/algebird/DecayedValueLaws.scala, algebird-test/src/test/scala/com/twitter/algebird/DecayedVectorProperties.scala, algebird-test/src/test/scala/com/twitter/algebird/FunctionMonoidTests.scala, algebird-test/src/test/scala/com/twitter/algebird/HyperLogLogSeriesTest.scala, algebird-test/src/test/scala/com/twitter/algebird/HyperLogLogTest.scala, algebird-test/src/test/scala/com/twitter/algebird/MetricProperties.scala, algebird-test/src/test/scala/com/twitter/algebird/MinHasherTest.scala, algebird-test/src/test/scala/com/twitter/algebird/MomentsLaws.scala, algebird-test/src/test/scala/com/twitter/algebird/SketchMapTest.scala, algebird-test/src/test/scala/com/twitter/algebird/SpaceSaverTest.scala, algebird-test/src/test/scala/com/twitter/algebird/TopKTests.scala, algebird-util/src/main/scala/com/twitter/algebird/util/UtilAlgebras.scala, algebird-util/src/test/scala/com/twitter/algebird/util/UtilAlgebraProperties.scala
This PR comes after #579. Closes #528. 
- Addresses #548 by deprecating the group/ring instances for future/try
- Adds actual tests for the monoid and semigroup instances for `Future` and `Try`
- updates the generators for `Future` and `Try` to include exceptional cases
- Adds an `Equiv` version to all remaining laws
- activates tests for `Batched` and `TopCMS`, which weren't running
- adds implicit `Equiv` instances for SpaceSaver and SketchMap
- tightens some tests to commutative
- moves `MetricProperties` into `src` so users can make use of `metricsLaws[T]`
=> Create Equiv versions of all laws, fix broken tests

CHANGES.md, algebird-benchmark/src/main/scala/com/twitter/algebird/benchmark/AveragedValueBenchmark.scala, algebird-benchmark/src/main/scala/com/twitter/algebird/benchmark/HLLBenchmark.scala, algebird-core/src/main/scala/com/twitter/algebird/AveragedValue.scala, algebird-core/src/main/scala/com/twitter/algebird/First.scala, algebird-core/src/main/scala/com/twitter/algebird/Last.scala, algebird-core/src/main/scala/com/twitter/algebird/Max.scala, algebird-core/src/main/scala/com/twitter/algebird/Min.scala, algebird-core/src/main/scala/com/twitter/algebird/MomentsGroup.scala, algebird-core/src/main/scala/com/twitter/algebird/Monoid.scala, algebird-core/src/main/scala/com/twitter/algebird/Semigroup.scala, algebird-test/src/test/scala/com/twitter/algebird/AveragedValueLaws.scala, build.sbt, docs/src/main/tut/datatypes/averaged_value.md, docs/src/main/tut/datatypes/first_and_last.md, docs/src/main/tut/datatypes/min_and_max.md
This PR increases test coverage and adds a documentation page for `AveragedValue`. It also adds a `sumOption` implementation. (This comes after #591, to take advantage of the benchmarking goodies.)
Run the benchmark with:
```
jmh:run -t1 -f 1 -wi 15 -i 20 .*AveragedValueBenchmark.*
```
Here are the results:
```
[info] Benchmark                             (numElements)   Mode  Cnt      Score      Error  Units
[info] AveragedValueBenchmark.timePlus               10000  thrpt   20   6474.320 ±   65.222  ops/s
[info] AveragedValueBenchmark.timeSumOption          10000  thrpt   15  15057.069 ±  305.026  ops/s
[success] Total time: 73 s, completed Dec 1, 2016 2:54:13 PM
```
So, about a 2.3x speedup from the optimized `sumOption` impl.
=> Coverage and documentation for AveragedValue
